### ISSUE TITLE
translationKey on multiline does not work

### ISSUE THREAD

**Issue by XiaotongW** [mxmvshnvsk/i18n-unused#36]
### Here are the package I'm using

- i18n-unused@0.13.0
- eslint@8.4.10
- vue@3.2.47
- vue-i18n@9.2.2

### Issue

When I'm running the following command 

```shell
i18m-unused display-unused
```
There a lot of translations keys which aren't unused.

#### Example

Here a examples of patter that do not work

```js
this.$t(
  'app.user.confirmation.delete',
  { user: 'MyUser' },
);

this.$t('app.user.confirmation.delete',
  { user: 'MyUser' });

this.$t('app.user.confirmation.delete',
  { user: 'MyUser' },
);
```

Here are example that work :
(_Unfortunately, I cannot place all my translation on a single line , because, I use eslint which force me to not have a ligne with length greater then 100._)

```js
this.$t('app.user.confirmation.delete', { user: 'MyUser' });
```

**Comment by andyl-ioki** [comment]
We have the same issue, that our linting rules forbid long lines.

So I dove a bit into the code and found the default matching regex: ` /(?:[$ .](_|t|tc))\(.*?\)/gi`
<img width="1126" alt="Screenshot 2023-10-24 at 11 00 58" src="https://github.com/mxmvshnvsk/i18n-unused/assets/102946449/80a1b54b-79f4-4903-a9e8-039b66fe7944">

After adding whitespace `[\n\r\s]` to the regex, it matches your other translations as well 👍 : ` /(?:[$ .](_|t|tc))\(([\n\r\s]|.)*?\)/gi`
<img width="1126" alt="Screenshot 2023-10-24 at 11 01 07" src="https://github.com/mxmvshnvsk/i18n-unused/assets/102946449/65685d2d-7cb7-4337-b47d-191e20c105b8">

---

The only thing you have to do is add the regex to your `i18n-unused.config.js`, so that it looks like this:
```js
module.exports = {
  ...
  translationKeyMatcher: /(?:[$ .](_|t|tc))\(([\n\r\s]|.)*?\)/gi,
};
```

---

Hope this helps 👍 

Thanks also for this project @mxmvshnvsk, I can create a PR for this as well to add the whitespace for the default regex. Wdyt?

**Comment by mxmvshnvsk** [comment]
Hi. Sounds great =)

**Comment by andyl-ioki** [comment]
> Hi. Sounds great =)

Done 👍
